# This file contains REST requests for the API that can be used with the
# REST Client extension for VS Code (https://marketplace.visualstudio.com/items?itemName=humao.rest-client)
# To use it, install the extension and then open this file in VS Code.
# You can then send the requests by clicking the "Send Request" link above each request.

@baseUrl = http://localhost:8080

### Get Health
GET {{baseUrl}}/health

### Get List of CatalogItems
GET {{baseUrl}}/catalogItems

### Get CatalogItem by ID
GET {{baseUrl}}/catalogItems/gpte.shared-workload-lpe-automation-controller.prod

### Start Provision
POST {{baseUrl}}/provision
Content-Type: application/json
Accept: application/json

{
    "Name": "test-auto-14.babylon-empty-config.prod",
    "ProviderName": "tests.babylon-empty-config.prod",
    "Purpose": "Testing",
    "Start": "2023-08-15T01:23:45Z",
    "Stop": "2023-08-16T01:23:45Z"
}

### Get Provision status
GET {{baseUrl}}/provision/test-auto-14.babylon-empty-config.prod

### Delete Provision
DELETE {{baseUrl}}/provision/test-auto-4.babylon-empty-config.prod
