# This file contains REST requests for the API that can be used with the
# REST Client extension for VS Code (https://marketplace.visualstudio.com/items?itemName=humao.rest-client)
# To use it, install the extension and then open this file in VS Code.
# You can then send the requests by clicking the "Send Request" link above each request.

@baseUrl = http://127.0.0.1:20001

### Get Health
GET {{baseUrl}}/health

### Get List of CatalogItems
GET {{baseUrl}}/catalogItems

### Get CatalogItem by ID
GET {{baseUrl}}/catalogItems/tests.babylon-empty-config.prod

### Start Provision
POST {{baseUrl}}/serviceRequest
Content-Type: application/json
Accept: application/json

{
    "Name": "test-auto-10.babylon-empty-config.prod",
    "ProviderName": "tests.babylon-empty-config.prod",
    "Purpose": "Testing",
    "Start": "2023-12-06T01:00:00Z",
    "Stop": "2023-12-07T01:00:00Z"
}

### Get Provision information
GET {{baseUrl}}/serviceRequest/test-auto-10.babylon-empty-config.prod

### Delete Provision
DELETE {{baseUrl}}/serviceRequest/test-auto-10.babylon-empty-config.prod

### Get ratings
GET {{baseUrl}}/ratings/tests.babylon-empty-config.prod

### Create rating
POST {{baseUrl}}/ratings
Content-Type: application/json
Accept: application/json

{
    "ProvisionName": "test-auto-10.babylon-empty-config.prod",
    "Email":"kmalgich@redhat.com",
    "Rating":40
}