## Code Genereation

https://cloud.redhat.com/blog/kubernetes-deep-dive-code-generation-customresources

. Install controller-gen:
+
-----------------------------------
go get sigs.k8s.io/controller-tools/cmd/controller-gen
go install sigs.k8s.io/controller-tools/cmd/controller-gen@latest
-----------------------------------

. Generate DeepCopy:
+
-----------------------------------
controller-gen object paths=./cmd/kube/apiextensions/v1/
-----------------------------------

## Runnign Locally

It is possible to run the Zero Touch API locally.

. Login to the target OpenShift cluster using 'oc login':
+
-----------------------------------
oc login https://api.crc.testing:6443
-----------------------------------

. Run the Zero Touch API locally using `go run` (KUBECONFIG environment variable must be set and point to a valid kubeconfig file):
+
-----------------------------------
KUBECONFIG=$HOME/.kube/config go run ./cmd
-----------------------------------

. Test the Zero Touch API using `curl`:
+
-----------------------------------
curl -i http://localhost:8080/health
-----------------------------------

### Using dotenv file

. Configuration can be done with a `.env` file (environemnt variables will ovverride options set at `.env` file):
+
-----------------------------------
KUBECONFIG=/home/user/.kube/config
RESOURCECLAIM_NAMESPACE=zerotouch-api
RECAPTCHA_DISABLED=true
-----------------------------------

## Development OpenShift Build

The OpenShift build process is a bit slower for development but has the advantage of being a bit closer to a normal deployment of the Zero Touch API.
It is often best to iterate development using `odo` and also test with an OpenShift build and deployment prior to opening a pull request.

. Create a project for development using `oc`:
+
-----------------------------------
oc new-project zerotouch-api-dev
-----------------------------------

. Process OpenShift build template to create BuildConfig and ImageStream:
+
---------------------------------------------------------
oc process --local -f build-template.yaml | oc apply -f -
---------------------------------------------------------

. Build zerotouch-api image from local source:
+
-----------------------------------------------------
oc start-build zerotouch-api --from-dir=. --follow
-----------------------------------------------------

. Deploy Poolboy from build image
+
--------------------------------------------------------------------------------
helm template helm \
--set nameOverride=zerotouch-api-dev \
--set namespace.create=false \
--set ingressDomain="apps-crc.testing" \
--set googleRecaptcha.authKey=" " \
--set image.override="$(oc get imagestream zerotouch-api -o jsonpath='{.status.tags[?(@.tag=="latest")].items[0].dockerImageReference}')" \
| oc apply -f -
--------------------------------------------------------------------------------

. Cleanup
+
Remove resources created from the helm template:
+
---------------------------------------------
helm template helm \
--set nameOverride=zerotouch-api-dev \
--set namespace.create=false \
--set ingressDomain="apps-crc.testing" \
| oc delete -f -
---------------------------------------------
+
Remove BuildConfig and ImageStream:
+
----------------------------------------------------------
oc process --local -f build-template.yaml | oc delete -f -
----------------------------------------------------------
