kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: catalogitems-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: zerotouch-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: catalogitems-reader