apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}
  strategy:
    type: {{ .Values.deployment.strategy }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appName }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: zerotouch-api
        image: {{ .Values.deployment.image }}:{{ .Values.image_tag | default .Values.deployment.tag }}
        imagePullPolicy: {{ .Values.deployment.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
