apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zerotouch-api.name" . }}
  namespace: {{ include "zerotouch-api.namespaceName" . }}
  labels:
    {{- include "zerotouch-api.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "zerotouch-api.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "zerotouch-api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "zerotouch-api.serviceAccountName" . }}
      containers:
      - name: zerotouch-api
        image: {{ include "zerotouch-api.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
      - name: swagger-ui
        image: swaggerapi/swagger-ui
        env:
        - name: SWAGGER_JSON_URL
          value: http://{{ include "zerotouch-api.namespaceName" . }}.{{ .Values.ingressDomain }}/swagger.json
        - name: PORT
          value: "8081"
        - name: VALIDATOR_URL
          value: ""
        ports:
        - containerPort: 8081
