---
{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zerotouch-api.name" . }}
  namespace: {{ include "zerotouch-api.namespaceName" . }}
  labels:
    {{- include "zerotouch-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "zerotouch-api.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "zerotouch-api.serviceAccountName" . }}
    namespace: {{ include "zerotouch-api.namespaceName" . }}
{{- end}}