---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "zerotouch-api.name" . }}
  namespace: {{ include "zerotouch-api.namespaceName" . }}
  labels:
    {{- include "zerotouch-api.labels" . | nindent 4 }}
spec:
  host: {{ include "zerotouch-api.namespaceName" . }}.{{ .Values.ingressDomain }}
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ include "zerotouch-api.name" . }}
  wildcardPolicy: None
