apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $k, $v := .Values.service.port }}
  - name: {{ $k }}
    protocol: TCP
    port: {{ $v }}
    targetPort: {{ $v }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}