---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zerotouch-api.name" . }}
  namespace: {{ include "zerotouch-api.namespaceName" . }}
  labels:
    {{- include "zerotouch-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $k, $v := .Values.service.port }}
  - name: {{ $k }}
    protocol: TCP
    port: {{ $v }}
    targetPort: {{ $v }}
  {{- end }}
  selector:
    {{- include "zerotouch-api.selectorLabels" . | nindent 4 }}