openapi: 3.0.3
info:
  title: Swagger Zero Touch API - OpenAPI 3.0
  description: API to manage Catalog Items as a part of Zero Touch POC
  version: 1.0.0
  
servers:
  - url: http://localhost:8080
  
components:
  schemas:
    CatalogItem:
      type: object
      properties:
        id:
          type: string
        Name:
          type: string
        DisplayName:
          type: string
        Description:
          type: string
        DescriptionFormat:
          type: string
      required:
        - id
        - Name
        - DisplayName
        - Description
        - DescriptionFormat
    Status:
      type: object
      properties:
        status:
          type: string
          enum:
            - OK
            - ERROR
        message:
          type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
      required:
        - code
        - message

paths:
  /health:
    get:
      summary: Health check
      description: Health check
      operationId: health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'

  /catalogItems:
    get:
      summary: List all Catalog Items
      description: List all Catalog Items
      operationId: listCatalogItems
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CatalogItem'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /catalogItems/{name}:
    get:
      summary: Get a Catalog Item
      description: Get a Catalog Item by Name
      operationId: getCatalogItem
      parameters:
        - name: name
          in: path
          description: Catalog Item Name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogItem'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'