package v1

import "k8s.io/apimachinery/pkg/runtime"

// TODO: Autogerate these functions
//
// Normally these functions should be autogenerated by the
// deepcopy-gen tool.
// See https://pkg.go.dev/k8s.io/gengo/examples/deepcopy-gen for more details.
//

//-----------------------------------------------------------------------------
// Catalog Item
//-----------------------------------------------------------------------------

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *CatalogItem) DeepCopyInto(out *CatalogItem) {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	// out.Spec = CatalogItemSpec{
	// 	Replicas: in.Spec.Replicas,
	// }
}

// DeepCopyObject returns a generically typed copy of an object
func (in *CatalogItem) DeepCopyObject() runtime.Object {
	out := CatalogItem{}
	in.DeepCopyInto(&out)

	return &out
}

// DeepCopyObject returns a generically typed copy of an object
func (in *CatalogItemList) DeepCopyObject() runtime.Object {
	out := CatalogItemList{}
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta

	if in.Items != nil {
		out.Items = make([]CatalogItem, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}

	return &out
}

//-----------------------------------------------------------------------------
// Resource Claims
//-----------------------------------------------------------------------------

// func (in *ResourceClaim) DeepCopyInto(out *ResourceClaim) {
// 	out.TypeMeta = in.TypeMeta
// 	out.ObjectMeta = in.ObjectMeta

// }

// func (in *ResourceClaim) DeepCopyObject() runtime.Object {
// 	out := ResourceClaim{}
// 	in.DeepCopyInto(&out)

// 	return &out
// }

// func (in *ResourceClaimList) DeepCopyObject() runtime.Object {
// 	out := ResourceClaimList{}
// 	out.TypeMeta = in.TypeMeta
// 	out.ListMeta = in.ListMeta

// 	if in.Items != nil {
// 		out.Items = make([]ResourceClaim, len(in.Items))
// 		for i := range in.Items {
// 			in.Items[i].DeepCopyInto(&out.Items[i])
// 		}
// 	}

// 	return &out
// }
